### ISSUE TITLE
the latest release I think above 1.0.2.0 can only using the default port 161, if using other port, the Invoke-SnmpWalk will always return null

### ISSUE THREAD

**Issue by skysunmonk** [Proxx/Proxx.SNMP#1]
the latest release I think above 1.0.2.0 can only using the default port 161, if using other port, the Invoke-SnmpWalk will always return null

**Comment by skysunmonk** [comment]
pls help to check this

**Comment by skysunmonk** [comment]
@Proxx

**Comment by Proxx** [comment]
@skysunmonk its been 5years since my latest update to the project.
i will give it a quick look. but if i'm unable to trace the problem quickly i think you have to use the software as-is...

**Comment by Proxx** [comment]
whoops i think i found the problem 👍

**Comment by Proxx** [comment]
@skysunmonk can you overwrite Proxx.SNMP.dll with the dll i just pushed to the repo and try again?

**Comment by skysunmonk** [comment]
yes, I also try to fixed this issue by myself to add the port parameter, I think it works

**Comment by skysunmonk** [comment]
Thanks for you quick response
